class AlahliAcademyData {
  static List<Map<String, dynamic>> alahliAcademyData = [
    {
      'N0': 'AH1',
      'English Name': 'Omar Saeed Hassan Qambar',
      'Arabic Name': 'عمر سعيد حسن قمبر',
      'DATE OF BIRTH': '4/3/2010',
      'Position': 'مدافع ايسر',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U13',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH2',
      'English Name': 'Mohamed Zine El Abidine Abdel Fattah',
      'Arabic Name': 'محمد زين العابدين عبد الفتاح',
      'DATE OF BIRTH': '',
      'Position': 'وسط مهاجم',
      'Nationality': 'مصر',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U13',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH3',
      'English Name': 'Salem Jamal Mohammed',
      'Arabic Name': 'سالم جمال محمد',
      'DATE OF BIRTH': '23/4/2010',
      'Position': 'وسط ملعب',
      'Nationality': 'اليمن',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U13',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH4',
      'English Name': 'Juma Happy Juma',
      'Arabic Name': 'جمعة سعيد جمعة',
      'DATE OF BIRTH': '17/12/2010',
      'Position': 'وسط ملعب',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U13',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH5',
      'English Name': 'Abdul Aziz Hassan Al-Ali',
      'Arabic Name': 'عبد العزيز حسن العلي',
      'DATE OF BIRTH': '1/7/2010',
      'Position': 'مهاجم',
      'Nationality': 'سوريا',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U13',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH6',
      'English Name': 'Saleh Adnan Muhammad Mohsen',
      'Arabic Name': 'صالح عدنان محمد محسن',
      'DATE OF BIRTH': '',
      'Position': 'وسط ملعب',
      'Nationality': 'اليمن',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U13',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH7',
      'English Name': 'Faris Ali Abdullah Muhammad Ali',
      'Arabic Name': 'فارس علي عبد الله محمد علي',
      'DATE OF BIRTH': '19/03/2009',
      'Position': 'مهاجم',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH8',
      'English Name': 'Abdullah Awad Saeed Awad Al-Amiri',
      'Arabic Name': 'عبد الله عوض سعيد عوض العامري',
      'DATE OF BIRTH': '19/1/2009',
      'Position': 'قلب دفاع',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH9',
      'English Name': 'Muhammad Abdul Rahman Musa Hassan Ashour',
      'Arabic Name': 'محمد عبد الرحمن موسى حسن عاشور',
      'DATE OF BIRTH': '1/3/2009',
      'Position': 'مدافع أيمن',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH10',
      'English Name': 'Hamad Ahmed Omar Salem',
      'Arabic Name': 'حمد أحمد عمر سالم',
      'DATE OF BIRTH': '2/9/2009',
      'Position': 'وسط ملعب',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH11',
      'English Name': 'Mubarak Mohammed Abdullah Ibrahim Al-Bahr',
      'Arabic Name': 'مبارك محمد عبد الله إبراهيم البحر',
      'DATE OF BIRTH': '2/3/2009',
      'Position': 'حارس مرمى',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH12',
      'English Name': 'Muhammad Butti Muhammad',
      'Arabic Name': 'محمد بطي محمد',
      'DATE OF BIRTH': '30/1/2008',
      'Position': 'وسط مهاجم',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U15',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH13',
      'English Name': 'Muhammad Ahmed Ismail Mashmoum bin Farhan',
      'Arabic Name': 'محمد أحمد إسماعيل مشموم بن فرحان',
      'DATE OF BIRTH': '13/03/2008',
      'Position': 'وسط مهاجم',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U15',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH14',
      'English Name': 'Muhammad Iyad Jalal Al-Hanafi',
      'Arabic Name': 'محمد اياد جلال الحنفي',
      'DATE OF BIRTH': '9/11/2008',
      'Position': 'وسط مهاجم',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U15',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH15',
      'English Name': 'Ziyad Imad Ezzat Muhammad Shaltout',
      'Arabic Name': 'زياد عماد عزت محمد شلتوت',
      'DATE OF BIRTH': '27/7/2008',
      'Position': 'مهاجم',
      'Nationality': 'الأردن',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U15',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH16',
      'English Name': 'Muhammad Yusuf Baqer',
      'Arabic Name': 'محمد يوسف باقر',
      'DATE OF BIRTH': '20/9/2008',
      'Position': 'حارس مرمى',
      'Nationality': 'مصر',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U15',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH17',
      'English Name': 'Abdullah Ahmed Abdullah',
      'Arabic Name': 'عبد الله احمد عبد الله',
      'DATE OF BIRTH': '13/01/2008',
      'Position': 'قلب دفاع',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U15',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH18',
      'English Name': 'Mohammed Rashid Hamid Al-Kiwani',
      'Arabic Name': 'محمد راشد حميد الكيواني',
      'DATE OF BIRTH': '22/10/2007',
      'Position': 'وسط ملعب',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH19',
      'English Name': 'Khalifa Muhammad Al-Sabousi',
      'Arabic Name': 'خليفة محمد السبوسي',
      'DATE OF BIRTH': '12/6/2007',
      'Position': 'وسط يمين',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH20',
      'English Name': 'Muhammad Khairy Khalfan Al Hammadi',
      'Arabic Name': 'محمد خيري خلفان الحمادي',
      'DATE OF BIRTH': '17/02/2007',
      'Position': 'حارس مرمى',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH21',
      'English Name': 'Muhammad Hatem Ali Farouk Ali',
      'Arabic Name': 'محمد حاتم علي فاروق علي',
      'DATE OF BIRTH': '17/2/2007',
      'Position': 'مهاجم',
      'Nationality': 'الهند',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH22',
      'English Name': 'Muhammad Ali Al-Asbahi',
      'Arabic Name': 'محمد علي  الأصبحي',
      'DATE OF BIRTH': '10/11/2007',
      'Position': 'وسط ملعب',
      'Nationality': 'اليمن',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH23',
      'English Name': 'Abdullah Issa Ismail Balabd',
      'Arabic Name': 'عبد الله عيسى إسماعيل بالعبد',
      'DATE OF BIRTH': '4/10/2007',
      'Position': 'قلب دفاع',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH24',
      'English Name': 'Ghaith Abdullah Hassan Mahiwa',
      'Arabic Name': 'غيث عبد الله حسن محيوة',
      'DATE OF BIRTH': '25/03/2006',
      'Position': 'وسط يمين',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH25',
      'English Name': 'Ali Jaber Muhammad Abbas Sayyah',
      'Arabic Name': 'علي جابر محمد عباس صياح',
      'DATE OF BIRTH': '7/2/2006',
      'Position': 'وسط ملعب',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH26',
      'English Name': 'Hamid Abdullah Hassan Mahiwa',
      'Arabic Name': 'حميد عبد الله حسن محيوة',
      'DATE OF BIRTH': '6/11/2006',
      'Position': 'وسط',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH27',
      'English Name': 'Ali Adnan Muhammad Mohsen',
      'Arabic Name': 'علي عدنان محمد محسن',
      'DATE OF BIRTH': '11/11/2006',
      'Position': 'وسط مهاجم',
      'Nationality': 'اليمن',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH28',
      'English Name': 'Ahmed Hassan bin Ketah',
      'Arabic Name': 'احمد حسن بن كته',
      'DATE OF BIRTH': '21/06/2007',
      'Position': 'مدافع ايسر',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH29',
      'English Name': 'Khalifa Muhammad Ali Al-Dhanhani',
      'Arabic Name': 'خليفة محمد علي الظنحاني',
      'DATE OF BIRTH': '8/2/2006',
      'Position': 'مدافع ايسر',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'AH30',
      'English Name': 'Muhammad Juma Abdullah Al-Mansoori',
      'Arabic Name': 'محمد جمعه عبد الله المنصوري',
      'DATE OF BIRTH': '30/05/2006',
      'Position': 'وسط مهاجم',
      'Nationality': 'الامارات',
      'Team': 'نادي شباب الأهلي',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },

  ];
}