class HattaAcademyData {
  static List<Map<String, dynamic>> hattaAcademyData = [
    {
      'N0': 'HT1',
      'English Name': 'AHMED ALBADWAWI',
      'Arabic Name': 'احمد البدوي',
      'DATE OF BIRTH': '19/01/2006',
      'Position': 'جناح',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT2',
      'English Name': 'KHAMIS  ALBADWAWI',
      'Arabic Name': 'خميس البدوي',
      'DATE OF BIRTH': '1/5/2007',
      'Position': 'مهاجم',
      'Nationality': 'عمان',
      'Team': 'نادي حتا',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT3',
      'English Name': 'MUSAED KASHAN',
      'Arabic Name': 'مساعد كاشان',
      'DATE OF BIRTH': '15/04/2006',
      'Position': 'وسط',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT4',
      'English Name': 'ABDULLAH ALMEWAWIEI',
      'Arabic Name': 'عبدالله المويوي',
      'DATE OF BIRTH': '14/06/2006',
      'Position': 'مدافع',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT5',
      'English Name': 'NASSER  ALKAABI',
      'Arabic Name': 'ناصر الكعبي',
      'DATE OF BIRTH': '1/5/2007',
      'Position': 'ظهير أيسر',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT6',
      'English Name': 'NAWAF BAKHIT',
      'Arabic Name': 'نواف بخيت',
      'DATE OF BIRTH': '16/11/2006',
      'Position': '',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT7',
      'English Name': 'AHMED ALBADWAWI',
      'Arabic Name': 'احمد البدوي',
      'DATE OF BIRTH': '21/11/2006',
      'Position': 'حارس مرمى',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT8',
      'English Name': 'SAIF  ALKAABI',
      'Arabic Name': 'سيف الكعبي',
      'DATE OF BIRTH': '15/03/2006',
      'Position': 'حارس مرمى',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U17',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT9',
      'English Name': 'MARWAN ALMAZROUAL',
      'Arabic Name': 'مروان المزروع',
      'DATE OF BIRTH': '1/5/2007',
      'Position': 'مهاجم',
      'Nationality': 'عمان',
      'Team': 'نادي حتا',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT10',
      'English Name': 'SULTAN ALBEDWAWI',
      'Arabic Name': 'سلطان البدواوي',
      'DATE OF BIRTH': '28/04/2008',
      'Position': 'وسط',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT11',
      'English Name': 'MOHAMMED MUBARAF',
      'Arabic Name': 'محمد مبارك',
      'DATE OF BIRTH': '7/3/2008',
      'Position': 'وسط',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT12',
      'English Name': 'ABDELRAHMAN MOHAMED',
      'Arabic Name': 'عبد الرحمن محمد',
      'DATE OF BIRTH': '21/01/2008',
      'Position': 'مدافع',
      'Nationality': 'السودان',
      'Team': 'نادي حتا',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT13',
      'English Name': 'NAYEF  BAKHIT',
      'Arabic Name': 'نايف بخيت',
      'DATE OF BIRTH': '1/11/2007',
      'Position': 'مدافع',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT14',
      'English Name': 'MANSOOR ALMEQBALI',
      'Arabic Name': 'منصور المقبالي',
      'DATE OF BIRTH': '6/6/2008',
      'Position': 'حارس مرمى',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT15',
      'English Name': 'SAIF  ALBADWAWI',
      'Arabic Name': 'سيف البدوي',
      'DATE OF BIRTH': '15/03/2006',
      'Position': 'حارس مرمى',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U16',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT16',
      'English Name': 'OBAID ALKABI',
      'Arabic Name': 'عبيد الكابي',
      'DATE OF BIRTH': '12/9/2009',
      'Position': 'جناح',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT17',
      'English Name': 'KHALED EMARA',
      'Arabic Name': 'خالد عمارة',
      'DATE OF BIRTH': '20/08/2009',
      'Position': 'وسط',
      'Nationality': 'مصر',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT18',
      'English Name': 'HAMDAN IBRAHM',
      'Arabic Name': 'حمدان ابراهيم',
      'DATE OF BIRTH': '21/01/2009',
      'Position': 'وسط',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT19',
      'English Name': 'ZAYED  SEBAIT',
      'Arabic Name': 'زايد سبيت',
      'DATE OF BIRTH': '24/03/2010',
      'Position': 'وسط',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT20',
      'English Name': 'SHAMIS MUBARAK',
      'Arabic Name': 'شميس مبارك',
      'DATE OF BIRTH': '10/4/2009',
      'Position': 'مدافع',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT21',
      'English Name': 'ABDALAZEEZ KASHAN',
      'Arabic Name': 'عبد العزيز كاشان',
      'DATE OF BIRTH': '9/6/2009',
      'Position': 'مدافع',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT22',
      'English Name': 'HAMAD ALHATTAWI',
      'Arabic Name': 'حمد الحطوي',
      'DATE OF BIRTH': '23/10/2009',
      'Position': 'ظهير أيسر',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT23',
      'English Name': 'MOHAMMED ALBDEDWAWI',
      'Arabic Name': 'محمد البداوي',
      'DATE OF BIRTH': '26/06/2010',
      'Position': 'ظهير أيمن',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },
    {
      'N0': 'HT24',
      'English Name': 'MANSOOR ALHATTAWI',
      'Arabic Name': 'منصور الحطوي',
      'DATE OF BIRTH': '17/03/2009',
      'Position': 'حارس مرمى',
      'Nationality': 'الإمارات',
      'Team': 'نادي حتا',
      'Age': 'U14',
      'Sport': 'كرة القدم',
    },


  ];
}