class PrivateAcademiesData {
  static List<Map<String, dynamic>> privateAcademiesData = [
{
'N0': 'PR1',
'English Name': 'Adam el husseiny',
'Arabic Name': 'ادم الحسينى',
'DATE OF BIRTH': '2004',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'City fc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR2',
'English Name': 'Mourad el zaher',
'Arabic Name': 'مراد الظاهر',
'DATE OF BIRTH': '2005',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'City fc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR3',
'English Name': 'Mohamed saleh',
'Arabic Name': 'محمد صالح',
'DATE OF BIRTH': '2005',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Foxes',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR4',
'English Name': 'Yousef Abdullah',
'Arabic Name': 'يوسف عبدالله',
'DATE OF BIRTH': '2006',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Iconz',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR5',
'English Name': 'Omar khaled',
'Arabic Name': 'عمر خالد',
'DATE OF BIRTH': '2006',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Nemo',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR6',
'English Name': 'ABDALLA TAMER',
'Arabic Name': 'عبد الله تامر',
'DATE OF BIRTH': '2006',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'ITTIFAQ',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR7',
'English Name': 'Mohamed Rayhan',
'Arabic Name': 'محمد ريحان',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Al ethihad',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR8',
'English Name': 'Salim',
'Arabic Name': 'سليم',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Alliance',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR9',
'English Name': 'Selim khairy',
'Arabic Name': 'سليم خيري',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Alliance',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR10',
'English Name': 'Ziyad Ammor',
'Arabic Name': 'زياد عمور',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'المغرب',
'Team': 'Barca',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR11',
'English Name': 'Rashed abdullah',
'Arabic Name': 'راشد عبدالله',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Falcon',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR12',
'English Name': 'Rayan Husam',
'Arabic Name': 'ريان حسام',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'Iconz',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR13',
'English Name': 'Maxence Gonnet',
'Arabic Name': 'ماكسينس جونيت',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'فرنسا',
'Team': 'Laliga White',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR14',
'English Name': 'Yohan Dmello',
'Arabic Name': 'يوهان دميلو',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Reds',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR15',
'English Name': 'Mohamed Husein',
'Arabic Name': 'محمد حسين',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'إيران',
'Team': 'Shabab Alahli',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR16',
'English Name': 'Yousif Amagd',
'Arabic Name': 'يوسف امجد',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Talent',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR17',
'English Name': 'Ahmad',
'Arabic Name': 'أحمد',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Talento',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR18',
'English Name': 'SHAYAAN ALAM',
'Arabic Name': 'شيان عالم',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'بريطانياا',
'Team': 'CFFA',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR19',
'English Name': 'ANTHONY KHAYAT',
'Arabic Name': 'أنطوني خياط',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'FURSAN',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR20',
'English Name': 'RAYAN DAHISH',
'Arabic Name': 'ريان داهيش',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'ICONZ',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR21',
'English Name': 'Hamd Ahmed',
'Arabic Name': 'حمد احمد',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Al nasr',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR22',
'English Name': 'Varun Binu',
'Arabic Name': 'فارون بينو',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Arabian Strikers',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR23',
'English Name': 'Ahmad Noah',
'Arabic Name': 'احمد نوح',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'Barca',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR24',
'English Name': 'Aahil Mohamed',
'Arabic Name': 'آهيل محمد',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Cffa',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR25',
'English Name': 'Abdullah',
'Arabic Name': 'عبد الله',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Ism',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR26',
'English Name': 'Malek el karoui',
'Arabic Name': 'مالك القروي',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'فرنسا',
'Team': 'Juventus',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR27',
'English Name': 'Adham Ali',
'Arabic Name': 'أدهم علي',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Nemo',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR28',
'English Name': 'Zeyad ahmad',
'Arabic Name': 'زياد احمد',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Nemo',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR29',
'English Name': 'Omar Khalil',
'Arabic Name': 'عمر خليل',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Star',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR30',
'English Name': 'Ishaan uella',
'Arabic Name': 'إيشان ويلا',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'بريطانيا',
'Team': 'Tfa',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR31',
'English Name': 'JADE AYA MAAN',
'Arabic Name': 'جايد آيا معان',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'فرنسا',
'Team': 'EMPIRE (Girls)',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR32',
'English Name': 'ZEYAD AHMED',
'Arabic Name': 'زياد احمد',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'NEMO',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR33',
'English Name': 'OMAR EL-NEFEIDI',
'Arabic Name': 'عمر النفيدي',
'DATE OF BIRTH': '2008',
'Position': 'N/A',
'Nationality': 'السودان',
'Team': 'TFA',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR34',
'English Name': 'Ziansha Muhammed',
'Arabic Name': 'زيانشا محمد',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Arabian Strikers',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR35',
'English Name': 'Youssef',
'Arabic Name': 'يوسف',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Falcon',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR36',
'English Name': 'Majd Alaa',
'Arabic Name': 'مجد علاء',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'سوريا',
'Team': 'Falcon',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR37',
'English Name': 'Taim Al Juber',
'Arabic Name': 'تيم الجبر',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'سوريا',
'Team': 'Juventus',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR38',
'English Name': 'Issam',
'Arabic Name': 'عصام',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Juventus - Rabiot',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR39',
'English Name': 'Omar Al Farouk',
'Arabic Name': 'عمر الفاروق',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'سوريا',
'Team': 'Olympic',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR40',
'English Name': 'Tyler salter',
'Arabic Name': 'تايلر سالتر',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'جنوب أفريقيا',
'Team': 'United fc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR41',
'English Name': 'NATHAAN HABEEB',
'Arabic Name': 'ناثان حبيب',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'CFFA',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR42',
'English Name': 'GABRIAL EL KHOURY',
'Arabic Name': 'جبريل الخوري',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'سلوفاكيا',
'Team': 'FURSAN',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR43',
'English Name': 'Ribal Andari',
'Arabic Name': 'ريبال أنداري',
'DATE OF BIRTH': '2010',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'La Liga',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR44',
'English Name': 'Ihab hassan',
'Arabic Name': 'ايهاب حسن',
'DATE OF BIRTH': '2010',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Prime talent',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR45',
'English Name': 'Basel Attafy',
'Arabic Name': 'باسل عطافي',
'DATE OF BIRTH': '2010',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Talented',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR46',
'English Name': 'POPPY HUNT',
'Arabic Name': 'صيد الخشخاش',
'DATE OF BIRTH': '2010',
'Position': 'N/A',
'Nationality': 'بريطانيا',
'Team': 'ALLIANCE (Girls)',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR47',
'English Name': 'BASHIR KHALID',
'Arabic Name': 'بشير خالد',
'DATE OF BIRTH': '2010',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'REGIONAL',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR48',
'English Name': 'Ethan Pader',
'Arabic Name': 'إيثان بادر',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'فرنسا',
'Team': 'Afc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR49',
'English Name': 'Damian',
'Arabic Name': 'داميان',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'هولندا',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR50',
'English Name': 'Ramzi Takeddin',
'Arabic Name': 'رمزي تقي الدين',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR51',
'English Name': 'Majd El Khatib',
'Arabic Name': 'مجد الخطيب',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR52',
'English Name': 'Ishaan Siyad',
'Arabic Name': 'إيشان سياد',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Arabian Strikers',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR53',
'English Name': 'Yash preetnarinderpel',
'Arabic Name': 'ياش بريتناريندربل',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Cffa',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR54',
'English Name': 'Youssef Bousahaba',
'Arabic Name': 'يوسف بوصحابه',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الجزائر',
'Team': 'Desert Falcon',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR55',
'English Name': 'Saif Sharaf',
'Arabic Name': 'سيف شرف',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Desert Falcon',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR56',
'English Name': 'Eric Zhang',
'Arabic Name': 'إريك تشانغ',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الصين',
'Team': 'Dragon TWelve',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR57',
'English Name': 'Ahmed Rabba',
'Arabic Name': 'احمد ربه',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'أمريكا',
'Team': 'El talento',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR58',
'English Name': 'Momen Bachaa',
'Arabic Name': 'مؤمن باشا',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'تونس',
'Team': 'El Talento',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR59',
'English Name': 'Noah Sprenger',
'Arabic Name': 'نوح سبرينجر',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'بريطانيا',
'Team': 'Empire FC',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR60',
'English Name': 'Nicolas ohrtmann',
'Arabic Name': 'نيكولاس أورتمان',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'ألمانيا',
'Team': 'Ism',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR61',
'English Name': 'Matteo caraliere',
'Arabic Name': 'ماتيو كاراليير',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'إيطاليا',
'Team': 'Ism',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR62',
'English Name': 'Youssed ghamgui',
'Arabic Name': 'يوسف غمقي',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'تونس',
'Team': 'Juventus',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR63',
'English Name': 'Youssef',
'Arabic Name': 'يوسف',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'تونس',
'Team': 'Juventus',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR64',
'English Name': 'Adham',
'Arabic Name': 'أدهم',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'La Liga White',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR65',
'English Name': 'Meckaline',
'Arabic Name': 'ميكالين',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'La Liga White',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR66',
'English Name': 'Sultan Al louzi',
'Arabic Name': 'سلطان اللوزي',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'Laliga hpc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR67',
'English Name': 'Rashid Elmasri',
'Arabic Name': 'رشيد المصري',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Reds',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR68',
'English Name': 'Omar DarWish',
'Arabic Name': 'عمر درويش',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'Talented',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR69',
'English Name': 'Rachid el chaar',
'Arabic Name': 'رشيد الشعار',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Tfa',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR70',
'English Name': 'ADAM KHALIL',
'Arabic Name': 'آدم خليل',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'REDS',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR71',
'English Name': 'CHRISTIAN MUGUMBATE',
'Arabic Name': 'كريستيان موغومبات',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'أمريكا',
'Team': 'TFA',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR72',
'English Name': 'Omar Jokhadar',
'Arabic Name': 'عمر جوخدار',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'سوريا',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR73',
'English Name': 'Nash Fernandes',
'Arabic Name': 'ناش فرنانديز',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Arabian Strikers',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR74',
'English Name': 'Adam',
'Arabic Name': 'آدم',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Champs',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR75',
'English Name': 'Alex',
'Arabic Name': 'اليكس',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Desert Faclon',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR76',
'English Name': 'Zhexuan Wang',
'Arabic Name': 'زيكوان وانغ',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'الصين',
'Team': 'Dragon TWelve FC',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR77',
'English Name': 'thedore saxby',
'Arabic Name': 'ثيودور ساكسبي',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'السويد',
'Team': 'Ism',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR78',
'English Name': 'Ismael Souid',
'Arabic Name': 'اسماعيل سويد',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'فرنسا',
'Team': 'Juventus Kean',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR79',
'English Name': 'Nidal bou',
'Arabic Name': 'نضال بو',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Laliga blue',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR80',
'English Name': 'Ricardo Ibrahim',
'Arabic Name': 'ريكاردو ابراهيم',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Olympiacos',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR81',
'English Name': 'Ahmed Salem',
'Arabic Name': 'احمد سالم',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'United Fc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR82',
'English Name': 'NASH KENRICK',
'Arabic Name': 'ناش كينريك',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'ARABIAN STRIKERS',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR83',
'English Name': 'Barni labsncz',
'Arabic Name': 'مختبرات بارني',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'المجر',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR84',
'English Name': 'Alonso Salcedo',
'Arabic Name': 'ألونسو سالسيدو',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'المكسيك',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR85',
'English Name': 'Tadej krstic',
'Arabic Name': 'تاديج كرستك',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'صربيا',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR86',
'English Name': 'Ismail Dialo',
'Arabic Name': 'اسماعيل ديالو',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'فرنسا',
'Team': 'Al nasr',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR87',
'English Name': 'Abdulaziz Khaled',
'Arabic Name': 'عبدالعزيز خالد',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'سلطنة عمان',
'Team': 'Al Wasl',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR88',
'English Name': 'Ali kazi',
'Arabic Name': 'علي قاضي',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Arabian strikers',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR89',
'English Name': 'Azim mohammed',
'Arabic Name': 'عظيم محمد',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Arabian strikers',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR90',
'English Name': 'Cristiano',
'Arabic Name': 'كريستيانو',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Cffa',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR91',
'English Name': 'Ali Abdelalim',
'Arabic Name': 'علي عبد العليم',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Falcon',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR92',
'English Name': 'Khaled SarataWy',
'Arabic Name': 'خالد سراطة',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'ألمانيا',
'Team': 'Falcon',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR93',
'English Name': 'Kaihan Kharouti',
'Arabic Name': 'كيهان الخروتي',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'بريطانيا',
'Team': 'La Liga Blue',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR94',
'English Name': 'Ghaith Ibrahim',
'Arabic Name': 'غيث ابراهيم',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'La Liga Blue',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR95',
'English Name': 'Mustafa Alterani',
'Arabic Name': 'مصطفى التراني',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'La Liga White',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR96',
'English Name': 'Nassimel Madiouni',
'Arabic Name': 'نسيم مديوني',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'بلجيكا',
'Team': 'La Liga White',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR97',
'English Name': 'Hamza Essa',
'Arabic Name': 'حمزة عيسى',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Talented',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR98',
'English Name': 'Khalid Ahmed',
'Arabic Name': 'خالد احمد',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'السودان',
'Team': 'Talented',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR99',
'English Name': 'ALI MAJDI',
'Arabic Name': 'علي المجدي',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'أمريكا',
'Team': 'GOLDEN STAR',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR100',
'English Name': 'OMAR KHALED',
'Arabic Name': 'عمر خالد',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'TALENTED',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR101',
'English Name': 'HAMZAH SAMEH',
'Arabic Name': 'حمزة سامح',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'TALENTED',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR102',
'English Name': 'Alessio',
'Arabic Name': 'اليسيو',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'إيطاليا',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR103',
'English Name': 'Abdullah',
'Arabic Name': 'عبد الله',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Al nasr',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR104',
'English Name': 'Rohan',
'Arabic Name': 'روهان',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Al Wasl',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR105',
'English Name': 'Omar amr',
'Arabic Name': 'عمر عمرو',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Al Wasl',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR106',
'English Name': 'Ahmed FeWou',
'Arabic Name': 'احمد فوفو',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'كندا',
'Team': 'Alliance',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR107',
'English Name': 'Rayan Carlos Du',
'Arabic Name': 'ريان كارلوس دو',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'أمريكا',
'Team': 'Dragon 12',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR108',
'English Name': 'Wosbeen',
'Arabic Name': 'وسبين',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'كوريا',
'Team': 'Ism',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR109',
'English Name': 'Omer guney',
'Arabic Name': 'عمر جوني',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'تركيا',
'Team': 'Ism',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR110',
'English Name': 'Mouhamed Adez',
'Arabic Name': 'محمد أديز',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'Juventus',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR111',
'English Name': 'Ishaaq Zamouri',
'Arabic Name': 'اسحق الزموري',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'المغرب',
'Team': 'La Liga Blue',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR112',
'English Name': 'Saad Obaid',
'Arabic Name': 'سعد عبيد',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Olympic',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR113',
'English Name': 'Essa Hamad',
'Arabic Name': 'عيسى حمد',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Shabab Al Ahili',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR114',
'English Name': 'Victore LWan',
'Arabic Name': 'انتصار LWan',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'رومانيا',
'Team': 'Shabab Al Ahili',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR115',
'English Name': 'Sayed Ali Hussein',
'Arabic Name': 'سيد علي حسين',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'الجزائر',
'Team': 'Shabab Al Ahli',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR116',
'English Name': 'Abdallah Jasim',
'Arabic Name': 'عبدالله جاسم',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Shabab Al Ahli',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR117',
'English Name': 'Jose',
'Arabic Name': 'جوزيه',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'أسبانيا',
'Team': 'TFA',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR118',
'English Name': 'OMER GUNEY',
'Arabic Name': 'عمر جوني',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'تركيا',
'Team': 'ISM',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR119',
'English Name': 'DENIZ SAKA',
'Arabic Name': 'دنيز ساكا',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'تركيا',
'Team': 'LA LIGA',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR120',
'English Name': 'Frederico Stella',
'Arabic Name': 'فريدريكو ستيلا',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'إيطاليا',
'Team': 'Afc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR121',
'English Name': 'Aman Ramallo',
'Arabic Name': 'أمان رامالو',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'إسبانيا',
'Team': 'Afc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR122',
'English Name': 'Yazid',
'Arabic Name': 'يزيد',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'تونس',
'Team': 'Afc',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR123',
'English Name': 'Ayrton pots',
'Arabic Name': 'أواني آيرتون',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'بلجيكا',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR124',
'English Name': 'Shadi Lamrani',
'Arabic Name': 'شادي العمراني',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'هولندا',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR125',
'English Name': 'Khaled al qasem',
'Arabic Name': 'خالد القاسم',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Al naser',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR126',
'English Name': 'Mohammed TaWfic',
'Arabic Name': 'محمد توفيق',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'نيجيريا',
'Team': 'Al Nasr',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR127',
'English Name': 'Julian Raphael',
'Arabic Name': 'جوليان رافائيل',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'بلجيكا',
'Team': 'Barca - Jordi',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR128',
'English Name': 'Haopeng Weng',
'Arabic Name': 'هاوبنغ ونغ',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'الصين',
'Team': 'Dragon TWelve FC',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR129',
'English Name': 'Kevin Harfauche',
'Arabic Name': 'كيفن هارفاوتشي',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Juventus',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR130',
'English Name': 'Kevin Harfoche',
'Arabic Name': 'كيفن هارفوش',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Juventus',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR131',
'English Name': 'Toufik Mansour',
'Arabic Name': 'توفيق منصور',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'أمريكا',
'Team': 'La Liga Blue',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR132',
'English Name': 'Vir Raghar',
'Arabic Name': 'فير راغر',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'La Liga White',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR133',
'English Name': 'Abdalziz omar',
'Arabic Name': 'عبد العزيز عمر',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Shabab al ahli',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR134',
'English Name': 'Ali Walid',
'Arabic Name': 'علي وليد',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Shabab al ahli',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR135',
'English Name': 'ADAM REDA',
'Arabic Name': 'آدم ريدا',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'LA LIGA',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR136',
'English Name': 'ELIE BAZZI',
'Arabic Name': 'إيلي بازي',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'LA LIGA',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR137',
'English Name': 'Essa Khaled',
'Arabic Name': 'عيسى خالد',
'DATE OF BIRTH': '2016',
'Position': 'N/A',
'Nationality': 'سلطنة عمان',
'Team': 'Al Wasl',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR138',
'English Name': 'Markel Gimaev',
'Arabic Name': 'ماركيل جيمايف',
'DATE OF BIRTH': '2019',
'Position': 'N/A',
'Nationality': 'الروسية',
'Team': 'Ajax',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR139',
'English Name': 'Ahmad Fadel',
'Arabic Name': 'احمد فاضل',
'DATE OF BIRTH': '2019',
'Position': 'N/A',
'Nationality': 'العراق',
'Team': 'Regional',
'Age': 'N/A',
'Sport': 'كرة القدم',
},
{
'N0': 'PR140',
'English Name': 'Lorenzo-Bandidi',
'Arabic Name': 'لورنزو بانديدي',
'DATE OF BIRTH': '2005',
'Position': 'N/A',
'Nationality': 'إيطاليا',
'Team': 'Wildcats',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR141',
'English Name': 'Hassan-Al-Shaiba',
'Arabic Name': 'حسن الشيبة',
'DATE OF BIRTH': '2006',
'Position': 'N/A',
'Nationality': 'الإمارات',
'Team': 'Al-Nasr',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR142',
'English Name': 'Wael-Sleiman',
'Arabic Name': 'وائل سليمان',
'DATE OF BIRTH': '2006',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'JAM',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR143',
'English Name': 'Ajna-Obradovic',
'Arabic Name': 'اجنا اوبرادوفيتش',
'DATE OF BIRTH': '2006',
'Position': 'N/A',
'Nationality': 'صربيا',
'Team': 'NBA',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR144',
'English Name': 'Alex-Matta',
'Arabic Name': 'اليكس ماتا',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'أمريكا',
'Team': 'Champs',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR145',
'English Name': 'Haya-El-Gamal',
'Arabic Name': 'هيا الجمل',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'JAM',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR146',
'English Name': 'Sanad-Ghazal',
'Arabic Name': 'سند غزال',
'DATE OF BIRTH': '2007',
'Position': 'N/A',
'Nationality': 'الأردن',
'Team': 'NBA',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR147',
'English Name': 'Ibrahim-Mohsen',
'Arabic Name': 'ابراهيم محسن',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'JAM',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR148',
'English Name': 'Jayden-Miranda',
'Arabic Name': 'جايدن ميراندا',
'DATE OF BIRTH': '2009',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Sharjah',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR149',
'English Name': 'Rohit-Aravind',
'Arabic Name': 'روهيت أرافيند',
'DATE OF BIRTH': '2010',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'JAM',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR150',
'English Name': 'Jaidaa-Ehab',
'Arabic Name': 'جيداء ايهاب',
'DATE OF BIRTH': '2010',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'Modern',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR151',
'English Name': 'Abdul-Karim-Nounou',
'Arabic Name': 'عبد الكريم نونو',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'البرازيل',
'Team': 'JAM',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR152',
'English Name': 'Lauryn-Rivera',
'Arabic Name': 'لورين ريفيرا',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الفلبين',
'Team': 'JAM',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR153',
'English Name': 'Matt-Da-Costa',
'Arabic Name': 'مات دا كوستا',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الفلبين',
'Team': 'Modern',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR154',
'English Name': 'Duyan-Miranda',
'Arabic Name': 'دويان ميراندا',
'DATE OF BIRTH': '2011',
'Position': 'N/A',
'Nationality': 'الهند',
'Team': 'Sharjah',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR155',
'English Name': 'Kevin-Halabi',
'Arabic Name': 'كيفن حلبي',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'Champs',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR156',
'English Name': 'Travis-Ramos',
'Arabic Name': 'ترافيس راموس',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'الفلبين',
'Team': 'Hoops-Dreams',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR157',
'English Name': 'Grant-Murray',
'Arabic Name': 'جرانت موراي',
'DATE OF BIRTH': '2012',
'Position': 'N/A',
'Nationality': 'أيرلندا',
'Team': 'NBA',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR158',
'English Name': 'Youssef-Hassan',
'Arabic Name': 'يوسف حسن',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'مصر',
'Team': 'JAM',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR159',
'English Name': 'Yahya-Tas',
'Arabic Name': 'يحيى طاس',
'DATE OF BIRTH': '2013',
'Position': 'N/A',
'Nationality': 'تركيا',
'Team': 'NBA',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR160',
'English Name': 'Joe-Helou',
'Arabic Name': 'جو حلو',
'DATE OF BIRTH': '2014',
'Position': 'N/A',
'Nationality': 'لبنان',
'Team': 'JAM',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
{
'N0': 'PR161',
'English Name': 'Brix-Eslabon',
'Arabic Name': 'بريكس اسلابون',
'DATE OF BIRTH': '2015',
'Position': 'N/A',
'Nationality': 'الفلبين',
'Team': 'NBA',
'Age': 'N/A',
'Sport': 'كرة سلة',
},
  ];
}
